name: Greetings
'on':
  - pull_request_target
  - issues
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          issue-message: Hello @${{ github.actor }},
            Thanks for creating this issue and contributing to NEWS-AGGREGATOR-PROJECT !
            We will review your issue soon and provide feedback. 
            
            If you're interested in working on this issue, make sure you get yourself assigned before starting your work.
          pr-message: Awesome work, @${{ github.actor }}! 🎉 Thank you for your contribution and efforts to enhance NEWS-AGGREGATOR-PROJECT ! 
            We will review your changes soon and provide feedback.
